### ISSUE TITLE
After server setup was complete I am getting 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Bracciata** [aws-quickstart/quickstart-drupal#17]
I am creating a Drupal 8 Server on a new VPC and believe the issue may result from the VPC CIDR as I am unsure what to input for it. Thank you!

**Comment by vsnyc** [comment]
I suspect this should no longer be an issue. Several folks have commented on https://github.com/aws-quickstart/quickstart-drupal/issues/11 that the quick start now works. Please retry and open a new issue if the error occurs. As far as the VPC CIDR goes, you can leave it at the default: 10.0.0.0/16 if deploying in a new VPC. If deploying in an existing VPC, it must match the VPC CIDR of that VPC.
