### ISSUE TITLE
General error after fresh Drupal 8 install due to CDN

### ISSUE THREAD

**Issue by andrzej-lumini** [aws-quickstart/quickstart-drupal#19]
When i've installed the template and tried to access to my site though browser, i've had a white screen with the message :
`The website encountered an unexpected error. Please try again later.`
When i've disabled the cdn module the site showed normally.

**Comment by andrzej-lumini** [comment]
when i inspect the watchdog logs i have this : 
`  1654085   05/Aug 11:48   php    Error      TypeError: Return value of Drupal\cdn\CdnSettings::getStreamWrappers() must be of the type array, null returned in    
                                             Drupal\cdn\CdnSettings->getStreamWrappers() (line 103 of /var/www/drupal/                                             
  1654084   05/Aug 11:48   php    Error      TypeError: Return value of Drupal\cdn\CdnSettings::getStreamWrappers() must be of the type array, null returned in    
                                             Drupal\cdn\CdnSettings->getStreamWrappers() (line 103 of /var/www/drupal/   `

**Comment by vsnyc** [comment]
@andrzej-lumini - sorry for the delay. I can confirm that there is an issue with Drupal 8 installation when `CloudFrontEnable` is set to `'true'`. The reason appears to be a segmentation fault when executing this command: https://github.com/aws-quickstart/quickstart-drupal/blob/de53d23bf5af0b05d4bfbb79c17a0890df361e43/templates/webserver.template.yaml#L927

Reading the drush compatibility table at https://docs.drush.org/en/8.x/install/#drupal-compatibility, my guess is that this started happening after the installed drupal version got ahead of `8.3`, but I'm not totally sure and could use help.

There are two workarounds at this time:
1. Set `CloudFrontEnable` to `'false'` and it would skip running the command above, but also skip creating CloudFront CDN.
2. Alternatively, remove the following lines: https://github.com/aws-quickstart/quickstart-drupal/blob/de53d23bf5af0b05d4bfbb79c17a0890df361e43/templates/webserver.template.yaml#L925-L930 from `webserver.template.yaml` and deploy the templates from GitHub following our [instructions](https://aws-quickstart.github.io/option1.html). This way you would have a working stack and can configure the CDN manually post install. I'm thinking of making this as the default.
