### ISSUE TITLE
Drush Support

### ISSUE THREAD

**Issue by dschmidtadv** [aws-quickstart/quickstart-drupal#20]
Does this stack include  Drush?

**Comment by dschmidtadv** [comment]
sudo /root/.composer/vendor/bin/drush  seems to do the trick...

**Comment by vsnyc** [comment]
Yes, Drush is included with the deployment. See https://github.com/aws-quickstart/quickstart-drupal/blob/de53d23bf5af0b05d4bfbb79c17a0890df361e43/templates/webserver.template.yaml#L719. The code does get executed as root, so you have to use sudo.
