### ISSUE TITLE
Consistantly fails on S3 - S3 error: The specified key does not exist.

### ISSUE THREAD

**Issue by vharabor** [aws-quickstart/quickstart-drupal#3]
I've made a bucket and key and entered those values during stack creation but I still the the S3 error.

I see this in the template 
"TemplateURL": {
                    "Fn::Sub": "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template"

Are all the temple paths supposed to exist already in S3?

**Comment by vsnyc** [comment]
Yes, they are supposed to exist. You can trying launch from the [Drupal Quick Start landing page](https://aws.amazon.com/quickstart/architecture/drupal/).

The VPC quick start is included as a git submodule, when cloning the repo, make sure you have cloned with the submodules before uploading the assets to your S3 bucket e.g.

`git clone --recurse-submodules git@github.com:aws-quickstart/quickstart-drupal.git`

**Comment by vsnyc** [comment]
Marking as closed

**Comment by kylanhurt** [comment]
Believe it or not I actually got this error when I incorrectly tried to grab the stream from my LOCAL file, so don't let that fool you.
