### ISSUE TITLE
How does code propagate with auto scaling?

### ISSUE THREAD

**Issue by if-kyle** [aws-quickstart/quickstart-drupal#4]
Hello,

Thank you very much for this detailed guide.  I have not used auto scaling and am trying to determine how code updates/theme pushes to drupal show on the new auto scaled systems that are created.

My team creates tags in git and pushes the drupal code out to our various web servers a few times a day.  It seems like autoscale would just have the last AMI image version of the git tag, and not the most recent.  Do you have any suggestions on how to best approach this problem?  Would the new autoscale server need to do a "check in" to see what the other web servers are on or store the git tag pointer in something like s3?

I'm not sure if I'm missing it in this repo or if that is just left for the reader to find a solution to.

Thanks!

**Comment by vsnyc** [comment]
The best way to approach this would be to modify the user-data of the EC2 instance to download the latest code artifacts. Although the AMI image version is static based on the latest code once the stack is launched, the user-data within it can be used to fetch new code/assets at runtime. You can fork this repo and then modify the resource:`DrupalAMIEC2Instance` cfn-init/user-data section and add new script/command to accomplish this/
