### ISSUE TITLE
Cant fire up to drupal CF stacks, second one fails on vpc creation.

### ISSUE THREAD

**Issue by gateway** [aws-quickstart/quickstart-drupal#6]
Hi, we are testing this CF stack, and are able to fire up and access the drupal install.  I wanted to fire up a 2nd one but it keeps failing and then rolling back.

Here is the error Im getting each time.

![image](https://user-images.githubusercontent.com/519563/39595545-ac871d34-4ec4-11e8-99f4-d400cf5b6bd4.png)

Any ideas on what could be wrong?

**Comment by gateway** [comment]
It stops here.. 
![image](https://user-images.githubusercontent.com/519563/39643458-b309c9e8-4f89-11e8-8fee-a7680b498129.png)

This could be due to my limited knowledge of vpc ip settings and ranges.. I used the default fo the first stack , and the same settings, but again no idea.. just failing here ..

**Comment by vsnyc** [comment]
The error is displayed in the first CREATE_FAILED line. "The maximum number of addresses has been reached" for AWS::EC2::EIP. You can request a service limit increase to allowed a higher number of Elastic IPs and retry.
